### ISSUE TITLE
Allure report is not showing defects on web Chrome

### ISSUE THREAD

**Issue by AlexTalashkevich** [allure-framework/allure-core#448]
I just recently faced with an issue that Chrome does not open my Allure report (Defects tab) generated by Jenkins, however IE11 opens fine
Moreover, the same report opens fine at local PC on Chrome. So the issue is only while looking it at Jenkins.

I see the following JS error in Console: 

```javascript
    Error: [$compile:tplrt] http://errors.angularjs.org/1.2.26/$compile/tplrt?p0=allureTable&p1=templates%2Ftable%2Ftable.html
        at Error (native)
        at http://mysite.example.com/jenkins/job/WebTestAutomation-UI/18/allure/webjars/angularjs/1.2.26/angular.min.js:6:450
        at http://mysite.example.com/jenkins/job/WebTestAutomation-UI/18/allure/webjars/angularjs/1.2.26/angular.min.js:60:173
        at http://mysite.example.com/jenkins/job/WebTestAutomation-UI/18/allure/webjars/angularjs/1.2.26/angular.min.js:72:199
        at F (http://mysite.example.com/jenkins/job/WebTestAutomation-UI/18/allure/webjars/angularjs/1.2.26/angular.min.js:100:187)
        at http://mysite.example.com/jenkins/job/WebTestAutomation-UI/18/allure/webjars/angularjs/1.2.26/angular.min.js:101:350
        at k.$eval (http://mysite.example.com/jenkins/job/WebTestAutomation-UI/18/allure/webjars/angularjs/1.2.26/angular.min.js:112:68)
        at k.$digest (http://mysite.example.com/jenkins/job/WebTestAutomation-UI/18/allure/webjars/angularjs/1.2.26/angular.min.js:109:168)
        at k.$apply (http://mysite.example.com/jenkins/job/WebTestAutomation-UI/18/allure/webjars/angularjs/1.2.26/angular.min.js:112:398)
        at h (http://mysite.example.com/jenkins/job/WebTestAutomation-UI/18/allure/webjars/angularjs/1.2.26/angular.min.js:72:454)
```

Changing version of Allure from 1.4.4 to 1.4.0 and below didn't help.

**Comment by just-boris** [comment]
Sometimes it happen when someone use `mod_pagespeed`. It shamelessly modifies our files and makes them unworkable.
We need a way to work around it and make `mod_pagespeed` to keep our files untouched

**Comment by vania-pooh** [comment]
I don't think we need to work around stuff like that because we give no guarantee about every piece of software Allure is used with.

**Comment by vania-pooh** [comment]
Closing because of inactivity. Please reopen if still relevant.
