### ISSUE TITLE
Attachment count in Test step is wrong

### ISSUE THREAD

**Issue by echoAlexey** [allure-framework/allure-core#518]
Screenshot:

http://prntscr.com/6fdf9x

Xml Source:
``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1425998820431" stop="1425998830936" version="1.4.8">
    <name>CLI_Tool_Environment_Variable_Use_Test_Suite</name>
    <title>CLI_Tool_Environment_Variable_Use_Test_Suite</title>
    <test-cases>
        <test-case start="1425998821264" stop="1425998830887" status="broken">
            <name>TAF_CLI_Tool_Func_002</name>
            <title>Check that environment variables are reset/unset after being set</title>
            <description type="text">User might have to unset/reset environment variable before proceeding with command execution</description>
            <failure>
                <message>RuntimeException: java.lang.reflect.InvocationTargetException</message>
                <stack-trace>java.lang.RuntimeException: java.lang.reflect.InvocationTargetException.. 1 more</stack-trace>
            </failure>
            <steps>
                <step start="1425998821269" stop="1425998830858" status="broken">
                    <name>openShell</name>
                    <title>openShell</title>
                    <attachments>
                        <attachment title="log.txt" source="b4040d70-7d05-4edb-aef0-5cad180acdbc-attachment.txt" type="text/plain" size="352"/>
                    </attachments>
                </step>
            </steps>
            <attachments>
                <attachment title="log.txt" source="fdac55f3-4a3a-4bb8-bab7-dfd7ea2a08f0-attachment.txt" type="text/plain" size="10602"/>
            </attachments>
            <labels>
                <label name="host" value="selix557bx.lmera.ericsson.se"/>
                <label name="thread" value="CLI_Tool_Environment_Variable_Use_Test_Suite.1"/>
                <label name="story" value="CIP-1018: As a Developer who wants to Test I want ability to set environment variables for CLI session"/>
                <label name="feature" value="TAF-Core"/>
                <label name="severity" value="critical"/>
                <label name="testId" value="TAF_CLI_Tool_Func_002"/>
            </labels>
        </test-case>
        <test-case start="1425998830935" stop="1425998830936" status="canceled">
            <name>tearDown</name>
            <title>tearDown</title>
            <failure>
                <message>NullPointerException: null</message>
                <stack-trace>java.lang.NullPointerException
	at com.ericsson.cifwk.taf.taffit.test.cases.cli.CliToolEnvironmentVariablesUseTest.tearDown(CliToolEnvironmentVariablesUseTest.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="selix557bx.lmera.ericsson.se"/>
                <label name="thread" value="CLI_Tool_Environment_Variable_Use_Test_Suite.1"/>
            </labels>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="TAF"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>


```

**Comment by baev** [comment]
@echoAlexey thanks for suggesting!

Fixed via #521
