### ISSUE TITLE
Fix issues with report properties

### ISSUE THREAD

**Issue by baev** [allure-framework/allure-core#543]
There are some problems with properties such as `allure.issues.tracker.pattern`

**Comment by lanwen** [comment]
```java
Caused by: java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract java.lang.String[] ru.yandex.qatools.properties.annotations.Resource$Classpath.value() (Found data of type class java.lang.String[allure.properties])
	at sun.reflect.annotation.AnnotationTypeMismatchExceptionProxy.generateException(AnnotationTypeMismatchExceptionProxy.java:57)
	at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:83)
	at com.sun.proxy.$Proxy22.value(Unknown Source)
	at ru.yandex.qatools.properties.providers.DefaultPropertyProvider.classpath(DefaultPropertyProvider.java:49)
	at ru.yandex.qatools.properties.providers.DefaultPropertyProvider.provide(DefaultPropertyProvider.java:22)
	at ru.yandex.qatools.properties.PropertyLoader.populate(PropertyLoader.java:28)
	at ru.yandex.qatools.properties.PropertyLoader.populate(PropertyLoader.java:23)
	at ru.yandex.qatools.allure.config.AllureConfig.<init>(AllureConfig.java:79)
	at ru.yandex.qatools.allure.config.AllureConfig.newInstance(AllureConfig.java:152)
	at ru.yandex.qatools.allure.Allure.getVersion(Allure.java:266)
```

**Comment by baev** [comment]
@lanwen the problem is how to compiler save annotations in byte code:

* **properties-loader 1.5**:  `@Resource.Classpath` has `String` type of value. In source code you can use only `@Resource.Classpath("something")`. And this code always compiled to `@Classpath("something")`.

*  **properties-loader 1.6**:  `@Resource.Classpath` has `String[]` type of value. In source you can use both ways -  `@Resource.Classpath("something")` or `@Resource.Classpath({"something"})`. But this source **always** compiled to `@Classpath({"something"})`. 

So, when when you use Allure (depends on properties 1.5) and properties 1.6 VM can not load `AllureConfig` - the byte code of this class contains `@Classpath("allure.properties")`, but it is invalid signature.

**Comment by baev** [comment]
@lanwen BTW I don't the right way to migrate annotations signature =( And I don't how to fix this issue now.

**Comment by baev** [comment]
fixed. For you can configure the report generation in Allure Jenkins plugin, Allure Teamcity plugin and Allure commandline as well
