### ISSUE TITLE
Can't set "jaxb.encoding" property to given marshaller

### ISSUE THREAD

**Issue by pozharko** [allure-framework/allure-core#544]
This error occures in allure v 1.4.11
```
14:54:01: [WARN] Can't set "jaxb.encoding" property to given marshaller
javax.xml.bind.PropertyException: jaxb.encoding must be a String
        at javax.xml.bind.helpers.AbstractMarshallerImpl.checkString(AbstractMarshallerImpl.java:427) ~[?:1.8.0_31]
        at javax.xml.bind.helpers.AbstractMarshallerImpl.setProperty(AbstractMarshallerImpl.java:333) ~[?:1.8.0_31]
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.setProperty(MarshallerImpl.java:527) ~[?:1.8.0_31]
        at ru.yandex.qatools.allure.utils.AllureResultsUtils.setPropertySafely(AllureResultsUtils.java:196) [allure-java-adaptor-api-1.4.11.jar:?]
        at ru.yandex.qatools.allure.utils.AllureResultsUtils.marshaller(AllureResultsUtils.java:168) [allure-java-adaptor-api-1.4.11.jar:?]
        at ru.yandex.qatools.allure.utils.AllureResultsUtils.writeTestSuiteResult(AllureResultsUtils.java:146) [allure-java-adaptor-api-1.4.11.jar:?]
        at ru.yandex.qatools.allure.utils.AllureResultsUtils.writeTestSuiteResult(AllureResultsUtils.java:134) [allure-java-adaptor-api-1.4.11.jar:?]
        at ru.yandex.qatools.allure.Allure.fire(Allure.java:190) [allure-java-adaptor-api-1.4.11.jar:?]
        at ru.yandex.qatools.allure.testng.AllureTestListener.onFinish(AllureTestListener.java:106) [allure-testng-adaptor-1.4.11.jar:?]
        at org.testng.TestRunner.fireEvent(TestRunner.java:1246) [testng-6.8.jar:?]
        at org.testng.TestRunner.afterRun(TestRunner.java:1039) [testng-6.8.jar:?]
        at org.testng.TestRunner.run(TestRunner.java:621) [testng-6.8.jar:?]
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:334) [testng-6.8.jar:?]
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329) [testng-6.8.jar:?]
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291) [testng-6.8.jar:?]
        at org.testng.SuiteRunner.run(SuiteRunner.java:240) [testng-6.8.jar:?]
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.8.jar:?]
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.8.jar:?]
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198) [testng-6.8.jar:?]
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1123) [testng-6.8.jar:?]
        at org.testng.TestNG.run(TestNG.java:1031) [testng-6.8.jar:?]

```

**Comment by shimkiv** [comment]
#541

**Comment by pozharko** [comment]
Thanks!

**Comment by varunsharma3110** [comment]
I am still getting this error. For which allure version is this fixed?

**Comment by varunsharma3110** [comment]
It is resolved. Please ignore
