### ISSUE TITLE
[nunit] [teamcity] [nunit-console] Formed an incorrect Allure report if run tests from the command line of TeamCity

### ISSUE THREAD

**Issue by BCR69** [allure-framework/allure-core#548]
I was faced with the following problem: I run the tests through NUnit console, using the command line of TeamCity. At the output I get the wrong Allure report: wrong status and no screenshots for errors. If run by hands through cmd, then the reports are generated correctly. Is there any solution to this problem?

Allurelog:

2015-03-30 15:03:53,535 [EventPumpThread] ERROR NUnitAllureAdapter.AllureEventListener - Exception in TestFinished "NUnit.Core.TestResult"
System.ComponentModel.Win32Exception (0x80004005): The handle is invalid
   at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize, CopyPixelOperation copyPixelOperation)
   at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize)
   at AllureCSharpCommons.Utils.AllureResultsUtils.TakeScreenShot()
   at NUnitAllureAdapter.AllureEventListener.TakeScreenshot()
   at NUnitAllureAdapter.AllureEventListener.TestFinished(TestResult result)

My configuration of runner tests in TC http://i.stack.imgur.com/ghDRE.png

**Comment by baev** [comment]
@BCR69 sorry for the delay. Core team doesn't have any Net developers so NUnit supported mostly be community. Is the problem still relevant? 

@allure-framework/csharp-developers any ideas?

**Comment by BCR69** [comment]
@baev Thanks for answer. Yes, I have not decided this issue :(

**Comment by aswhitehouse** [comment]
@baev @BCR69 I'm replying to you in my thread to solve this issue.

**Comment by baev** [comment]
Seems like I can close this one
