### ISSUE TITLE
"Unsupported major.minor version 51.0" running with maven, even though using java 1.7

### ISSUE THREAD

**Issue by derekberger** [allure-framework/allure-core#573]
Here is my version of java:

$ java -version
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)

Yet when trying to run from command line with maven, I get the following 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project psp: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test failed: There was an error in the forked process
[ERROR] java.lang.UnsupportedClassVersionError: ru/yandex/qatools/allure/testng/AllureTestListener : Unsupported major.minor version 51.0
[ERROR] at java.lang.ClassLoader.defineClass1(Native Method)
[ERROR] at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[ERROR] at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[ERROR] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[ERROR] at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[ERROR] at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[ERROR] at java.security.AccessController.doPrivileged(Native Method)
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[ERROR] at java.lang.Class.forName0(Native Method)
[ERROR] at java.lang.Class.forName(Class.java:249)
[ERROR] at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:346)
[ERROR] at java.util.ServiceLoader$1.next(ServiceLoader.java:428)
[ERROR] at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:961)
[ERROR] at org.testng.TestNG.initializeConfiguration(TestNG.java:896)
[ERROR] at org.testng.TestNG.run(TestNG.java:1031)
[ERROR] at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
[ERROR] at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
[ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

Here is dependency from *pom.xml*:

```xml
<dependency>
    <groupId>ru.yandex.qatools.allure</groupId>
    <artifactId>allure-testng-adaptor</artifactId>
    <version>1.4.11</version>
    <exclusions>
        <exclusion>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by baev** [comment]
@derekberger I guess your brother uses java 1.6. Could you please specify the result of `mvn --version` command?

**Comment by derekberger** [comment]
Hmmm looks like maven *is* holding on to 1.6

mvn --version
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 10:22:22-0500)
Maven home: /usr/local/apache-maven/apache-maven-3.1.1
Java version: 1.6.0_65, vendor: Apple Inc.
Java home: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
Default locale: en_US, platform encoding: MacRoman
OS name: "mac os x", version: "10.9.5", arch: "x86_64", family: "mac"

**Comment by derekberger** [comment]
Fixed. Thanks for speedy reply.

**Comment by Cosafina** [comment]
OK, so maven is holding on to 1.6 - how did you fix that?

**Comment by baev** [comment]
http://stackoverflow.com/questions/18813828/why-maven-use-jdk-1-6-but-my-java-version-is-1-7

**Comment by Cosafina** [comment]
Specifically, in Windows you need to "set JAVA_HOME=C:\Program Files\Java\jdk1.7.0_75".  Even though you already have your JAVA_HOME set to the jdk you want to use, you have to specifically set it in the command prompt if you want to run maven from the command prompt

**Comment by Eddy1028** [comment]
> Thanks baev! 
I take the `~/.mavenrc` solution.

Here is the .mavenrc file:
```export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home```

If you are using jenv on a mac, it can be:
```export JAVA_HOME="$HOME/.jenv/versions/`jenv version-name`"```
