### ISSUE TITLE
[ERROR] No implementation for org.eclipse.aether.RepositorySystem was bound.

### ISSUE THREAD

**Issue by pdf88** [allure-framework/allure-core#577]
It seems like report generation doesn't work since this morning. 
Tests run fine, but while executing maven site goal I get an error: 

WARNING: Error injecting: ru.yandex.qatools.allure.report.AllureReportMojo
com.google.inject.ProvisionException: Guice provision errors:
1) No implementation for org.eclipse.aether.RepositorySystem was bound.
  while locating ru.yandex.qatools.allure.report.AllureReportMojo
1 error
	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:974)

Yesterday it was okay, but today I get the same errors on the local mashine and on the server in Jenkins job. 
I've cleaned the .m2/org directory and download all the modules again, but this didn't help.
Please see the pom file example:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>lenovo.tests</groupId>
    <artifactId>tests</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <compiler.version>1.7</compiler.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <selenium.version>2.45.0</selenium.version>
        <surefire.version>2.18</surefire.version>
        <testng.version>6.8.8</testng.version>
        <allure.version>1.4.4</allure.version>
        <allure.maven.version>2.0</allure.maven.version>
        <aspectj.version>1.8.3</aspectj.version>
        <maven.source.version>2.4</maven.source.version>
        <maven.compiler.version>3.2</maven.compiler.version>
        <SQLconnector.version>5.1.34</SQLconnector.version>
        <junit.version>4.11</junit.version>
        <hamcrest.version>1.3</hamcrest.version>
        <connector.version>5.1.6</connector.version>
    </properties>

    <name>lenovo.tests</name>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
             <distribution>repo</distribution>
        </license>
    </licenses>

    <dependencies>
        <dependency>
            <groupId>ru.yandex.qatools.allure</groupId>
            <artifactId>allure-testng-adaptor</artifactId>
            <version>${allure.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

    	<dependency>
     	   <groupId>mysql</groupId>
     		   <artifactId>mysql-connector-java</artifactId>
      	  <version>${SQLconnector.version}</version>
  		  </dependency>

        <dependency>
            <scope>test</scope>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.version}</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-firefox-driver</artifactId>
            <version>${selenium.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-remote-driver</artifactId>
            <version>${selenium.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.maven.surefire</groupId>
            <artifactId>surefire-junit4</artifactId>
            <version>${surefire.version}</version>
        </dependency>

        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>${hamcrest.version}</version>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>${testng.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.jcraft</groupId>
            <artifactId>jsch</artifactId>
            <version>0.1.50</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20080701</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.3.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.codesnippets4all</groupId>
            <artifactId>quick-json</artifactId>
            <version>1.0.4</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.version}</version>
                <configuration>
                    <source>${compiler.version}</source>
                    <target>${compiler.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>${maven.source.version}</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        	 <plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>${surefire.version}</version>
				<configuration>
                    <properties>
                        <property>
                            
                            <name>usedefaultlisteners</name>
                            <value>false</value>
                        </property>
                        <property>
                            
                            <name>listener</name>
                            <value>lenovo.tests.utils.AllureListener</value>
                        </property>
                    </properties>

                    <includes>
                        <include>**/**.java</include>
                    </includes>
                    <testFailureIgnore>true</testFailureIgnore>
					<argLine>
						-javaagent:${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar
					</argLine>
                    <suiteXmlFiles>
                        <suiteXmlFile>resources/TestSuiteConfig.xml</suiteXmlFile>
                    </suiteXmlFiles>
				</configuration>

				<dependencies>
					<dependency>
						<groupId>org.aspectj</groupId>
						<artifactId>aspectjweaver</artifactId>
						<version>${aspectj.version}</version>
					</dependency>
				</dependencies>
			</plugin>
        </plugins>
    </build>

    
    <reporting>
        <excludeDefaults>true</excludeDefaults>
        <plugins>
            <plugin>
                  <groupId>ru.yandex.qatools.allure</groupId>
                  <artifactId>allure-maven-plugin</artifactId>
                <version>${allure.maven.version}</version>
            </plugin>
        </plugins>
    </reporting>
</project>

And  the console output: 

T E S T S
-------------------------------------------------------
Running TestSuite
[INFO] 
	--- TEST SUITE: Testing ACL for SSO logged in report-viewer ---
[STARTED] testAccessAPIGetAssociatedNominations at 19-05-15_10:45:59
[PASSED]  testAccessAPIGetAssociatedNominations at 19-05-15_10:46:01
[STARTED] testSearchNominationInTheList at 19-05-15_10:46:01
[PASSED]  testSearchNominationInTheList at 19-05-15_10:46:16
[STARTED] testAccessToViewNominationPage at 19-05-15_10:46:16
[PASSED]  testAccessToViewNominationPage at 19-05-15_10:46:23

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-site-plugin:3.0:site (default-site) @ tests ---
[INFO] configuring report plugin ru.yandex.qatools.allure:allure-maven-plugin:2.0
мая 19, 2015 10:46:38 AM org.sonatype.guice.bean.reflect.Logs$JULSink warn
WARNING: Error injecting: ru.yandex.qatools.allure.report.AllureReportMojo
com.google.inject.ProvisionException: Guice provision errors:

1) No implementation for org.eclipse.aether.RepositorySystem was bound.
  while locating ru.yandex.qatools.allure.report.AllureReportMojo

1 error
	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:974)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1000)
	at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:52)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:108)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:965)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1011)
	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:961)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
	at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:245)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
	at org.apache.maven.reporting.exec.DefaultMavenReportExecutor.getConfiguredMavenReport(DefaultMavenReportExecutor.java:318)
	at org.apache.maven.reporting.exec.DefaultMavenReportExecutor.buildReportPlugin(DefaultMavenReportExecutor.java:267)
	at org.apache.maven.reporting.exec.DefaultMavenReportExecutor.buildMavenReports(DefaultMavenReportExecutor.java:148)
	at org.apache.maven.plugins.site.AbstractSiteRenderingMojo.getReports(AbstractSiteRenderingMojo.java:240)
	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:121)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:18.963s
[INFO] Finished at: Tue May 19 10:46:38 EEST 2015
[INFO] Final Memory: 30M/369M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.0:site (default-site) on project tests: failed to get report for ru.yandex.qatools.allure:allure-maven-plugin: Unable to load the mojo 'report' (or one of its required components) from the plugin 'ru.yandex.qatools.allure:allure-maven-plugin:2.0': com.google.inject.ProvisionException: Guice provision errors:
[ERROR] 
[ERROR] 1) No implementation for org.eclipse.aether.RepositorySystem was bound.
[ERROR] while locating ru.yandex.qatools.allure.report.AllureReportMojo
[ERROR] at ClassRealm[plugin>ru.yandex.qatools.allure:allure-maven-plugin:2.0, parent: ClassRealm[plugin>org.apache.maven.plugins:maven-site-plugin:3.0, parent: sun.misc.Launcher$AppClassLoader@6d06d69c]]
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=ru.yandex.qatools.allure:allure-maven-plugin:2.0:report)
[ERROR] 
[ERROR] 1 error
[ERROR] role: org.apache.maven.plugin.Mojo
[ERROR] roleHint: ru.yandex.qatools.allure:allure-maven-plugin:2.0:report
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Process finished with exit code 1

**Comment by lanwen** [comment]
If you don't change the version of allure and allure-maven-plugin, nothing should change in process.

**Comment by baev** [comment]
@pdf88 Maven 3.1.1 or higher required for allure-maven-plugin

**Comment by pdf88** [comment]
mvn --version shows me Apache Maven 3.2.5. 
And I have maven site plugin v.3.4
What I'm doing wrong?

**Comment by baev** [comment]
Since 14 IDEA uses bundle maven 3.0.5.

**Comment by pdf88** [comment]
Yes, that's it! Thank you, you a lot of help!

**Comment by brobee** [comment]
Hi all, with maven 3.0.4 is not possible to generate allure report?

**Comment by baev** [comment]
> Hi all, with maven 3.0.4 is not possible to generate allure report?

you can use Allure 2 instead

**Comment by brobee** [comment]
Hi baev, thank you! Could you share a link with me regarding allure 2? Usage(I mean with maven dependency) is the same and can I use it with cucumber-jvm?

**Comment by brobee** [comment]
https://docs.qameta.io/allure/2.0/#_maven_5 According to this site, it is not clear how can I switch to Allure 2. Any help would be appreciated!

**Comment by eroshenkoam** [comment]
@brobee, Allure 2 is fully compatible with previous adapters, so you can install it and use as before: allure generate <path/to/allure-results>. 

Are you using Jenkins?

**Comment by brobee** [comment]
Will use it with teamcity. However, I was able to install newer version of maven. my only problem is now, the feature files (given when then) steps cannot be found in the report. Why? Apart from that, the broken tests are yellow, failed red and passed are green. is it possible to modify it? broken = failed, only red/green should be shown on the report. Thanks!
