### ISSUE TITLE
Allure Core build is failing on the Windows 7 machine

### ISSUE THREAD

**Issue by braimanm** [allure-framework/allure-core#600]
Allure Core build is failing during the maven test goal on the Windows 7 machine as there are some platform dependant issues in the testNG adaptor test classes in the deleteNotEmptyDirectory method. I'm using JDK 1.7.0_79 for windows x64.
Here is an exception stack trace:

java.nio.file.FileSystemException: C:\Users\mb\AppData\Local\Temp\allure-results8478753718489562051\7e2e4214-cf2e-45cb-8d04-753939383f7a-testsuite.xml: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1079)
	at ru.yandex.qatools.allure.testng.AllureTestListenerXmlValidationTest$1.visitFile(AllureTestListenerXmlValidationTest.java:68)
	at ru.yandex.qatools.allure.testng.AllureTestListenerXmlValidationTest$1.visitFile(AllureTestListenerXmlValidationTest.java:1)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:135)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:69)
	at java.nio.file.Files.walkFileTree(Files.java:2602)
	at java.nio.file.Files.walkFileTree(Files.java:2635)
	at ru.yandex.qatools.allure.testng.AllureTestListenerXmlValidationTest.deleteNotEmptyDirectory(AllureTestListenerXmlValidationTest.java:65)
	at ru.yandex.qatools.allure.testng.AllureTestListenerXmlValidationTest.tearDown(AllureTestListenerXmlValidationTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by baev** [comment]
Seems like it is related issue http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4171239

We should close all streams and writers before deleting the files.

**Comment by baev** [comment]
fixed in #666
