### ISSUE TITLE
Падает с таким файлом в Jenkins allure

### ISSUE THREAD

**Issue by prodigy007** [allure-framework/allure-core#656]
падает с таким файлом https://yadi.sk/d/xe62MHSmicUdM
Jenkins ver. 1.625
Allure Jenkins Plugin 2,7

C:\Program Files (x86)\NUnit 2.6.4\bin>exit 0 
Allure Report Generation: started
Allure Report Generation: find directories by mask [**/allure-results]
Allure Report Generation: found allure result directories [C:\Users\habibullin\.jenkins\workspace\15_autotest\allure-results]
Allure Report Generation: copy founded directories in directory [C:\Users\habibullin\.jenkins\workspace\15_autotest\allure5886445420788716250.tmp\results]
Allure Report Generation: generate report from directory [C:\Users\habibullin\.jenkins\workspace\15_autotest\allure5886445420788716250.tmp]
Allure Report Generation: proxy settings [active:'false', host:'null', port:'0', username:'null', password: '']
ERROR: Publisher 'Allure Report Generation' aborted due to exception: 
java.io.IOException: ru.yandex.qatools.allure.report.AllureReportBuilderException: java.lang.reflect.InvocationTargetException
	at ru.yandex.qatools.allure.jenkins.utils.ReportGenerator.invoke(ReportGenerator.java:50)
	at ru.yandex.qatools.allure.jenkins.utils.ReportGenerator.invoke(ReportGenerator.java:25)
	at hudson.FilePath.act(FilePath.java:991)
	at hudson.FilePath.act(FilePath.java:969)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:267)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:146)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Caused by: ru.yandex.qatools.allure.report.AllureReportBuilderException: java.lang.reflect.InvocationTargetException
	at ru.yandex.qatools.allure.report.AllureReportBuilder.processResults(AllureReportBuilder.java:133)
	at ru.yandex.qatools.allure.jenkins.utils.ReportGenerator.invoke(ReportGenerator.java:47)
	... 14 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at ru.yandex.qatools.allure.report.AllureReportBuilder.processResults(AllureReportBuilder.java:131)
	... 15 more
Caused by: ru.yandex.qatools.allure.data.ReportGenerationException: net.sf.saxon.event.NoOpenStartTagException: An attribute node (version) cannot be created after the children of the containing element
	at ru.yandex.qatools.allure.data.utils.XslTransformationUtils.applyTransformation(XslTransformationUtils.java:55)
	at ru.yandex.qatools.allure.data.utils.XslTransformationUtils.applyTransformation(XslTransformationUtils.java:44)
	at ru.yandex.qatools.allure.data.utils.XslTransformationUtils.applyTransformation(XslTransformationUtils.java:35)
	at ru.yandex.qatools.allure.data.utils.XslTransformationUtils.applyTransformations(XslTransformationUtils.java:29)
	at ru.yandex.qatools.allure.data.TestSuiteFiles.generateTestRun(TestSuiteFiles.java:50)
	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:39)
	... 20 more
Caused by: net.sf.saxon.event.NoOpenStartTagException: An attribute node (version) cannot be created after the children of the containing element
	at net.sf.saxon.event.NoOpenStartTagException.makeNoOpenStartTagException(NoOpenStartTagException.java:49)
	at net.sf.saxon.event.ComplexContentOutputter.attribute(ComplexContentOutputter.java:296)
	at net.sf.saxon.instruct.CopyOf.copyAttribute(CopyOf.java:572)
	at net.sf.saxon.instruct.Copy.processLeavingTail(Copy.java:221)
	at net.sf.saxon.instruct.Template.expand(Template.java:220)
	at net.sf.saxon.instruct.CallTemplate$CallTemplatePackage.processLeavingTail(CallTemplate.java:440)
	at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:317)
	at net.sf.saxon.instruct.ApplyTemplates.apply(ApplyTemplates.java:210)
	at net.sf.saxon.instruct.ApplyTemplates.processLeavingTail(ApplyTemplates.java:174)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:556)
	at net.sf.saxon.instruct.Instruction.process(Instruction.java:93)
	at net.sf.saxon.instruct.ElementCreator.processLeavingTail(ElementCreator.java:296)
	at net.sf.saxon.instruct.Template.applyLeavingTail(Template.java:203)
	at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:345)
	at net.sf.saxon.instruct.ApplyTemplates.apply(ApplyTemplates.java:210)
	at net.sf.saxon.instruct.ApplyTemplates.process(ApplyTemplates.java:170)
	at net.sf.saxon.instruct.ElementCreator.processLeavingTail(ElementCreator.java:296)
	at net.sf.saxon.instruct.Copy.processLeavingTail(Copy.java:217)
	at net.sf.saxon.instruct.Template.expand(Template.java:220)
	at net.sf.saxon.instruct.CallTemplate$CallTemplatePackage.processLeavingTail(CallTemplate.java:440)
	at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:317)
	at net.sf.saxon.instruct.ApplyTemplates.apply(ApplyTemplates.java:210)
	at net.sf.saxon.instruct.ApplyTemplates.processLeavingTail(ApplyTemplates.java:174)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:556)
	at net.sf.saxon.instruct.Instruction.process(Instruction.java:93)
	at net.sf.saxon.instruct.ElementCreator.processLeavingTail(ElementCreator.java:296)
	at net.sf.saxon.instruct.Template.applyLeavingTail(Template.java:203)
	at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:345)
	at net.sf.saxon.instruct.ApplyTemplates.defaultAction(ApplyTemplates.java:378)
	at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:333)
	at net.sf.saxon.Controller.transformDocument(Controller.java:1807)
	at net.sf.saxon.Controller.transform(Controller.java:1621)
	at ru.yandex.qatools.allure.data.utils.XslTransformationUtils.applyTransformation(XslTransformationUtils.java:52)
	... 25 more
Sending e-mails to: habibullin@megatec.ru
Finished: FAILURE

**Comment by baev** [comment]
@prodigy007 you need to specify the version of report to generate (better to use the last one, 1.4.17)

**Comment by prodigy007** [comment]
thx work with 1.4.0
