### ISSUE TITLE
NoSuchMethodError: ru.yandex.qatools.allure.data.AttachmentInfo.setName(Ljava/lang/String;)V

### ISSUE THREAD

**Issue by lanwen** [allure-framework/allure-core#658]
When using custom plugin in some cases i got:
Allure 1.4.16
allure maven plugin 2.2
plugin built against 1.4.15

```java
[INFO] Found Plugin [ru.yandex.qatools.allure.data.plugins.EnvironmentPlugin@7f57a7a4]
[INFO] Found Plugin [ru.lanwen.allure.PackagesPlugin@78805df3]
[ERROR] Can't generate allure report data
ru.yandex.qatools.allure.report.AllureReportBuilderException: java.lang.reflect.InvocationTargetException
        at ru.yandex.qatools.allure.report.AllureReportBuilder.processResults(AllureReportBuilder.java:188)
        at ru.yandex.qatools.allure.report.AllureReportMojo.executeReport(AllureReportMojo.java:123)
        at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:196)
        at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:219)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:319)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:135)
        at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
        at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at ru.yandex.qatools.allure.report.AllureReportBuilder.processResults(AllureReportBuilder.java:186)
        ... 28 more
Caused by: java.lang.NoSuchMethodError: ru.yandex.qatools.allure.data.AttachmentInfo.setName(Ljava/lang/String;)V
        at ru.yandex.qatools.allure.data.io.AttachmentReader$AttachmentInfoIterator.next(AttachmentReader.java:48)
        at ru.yandex.qatools.allure.data.io.AttachmentReader$AttachmentInfoIterator.next(AttachmentReader.java:1)
        at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:75)
        at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
        ... 33 more
```

**Comment by lanwen** [comment]
rebuild plugin against 1.4.16 fixes the problem. Is there any backward incompatible changes between `1.4.15 .. 1.4.16`?

**Comment by baev** [comment]
@lanwen yep, there is some internal changes on report side.
