### ISSUE TITLE
Jetty fails to start

### ISSUE THREAD

**Issue by chandannj76723** [allure-framework/allure-core#728]
Tests are running fine and the Allure report is generating fine.
But, when I try to start the Jetty server, I get an error.

```
2015-12-30 16:55:16.309:WARN:oejuc.AbstractLifeCycle:main: FAILED org.eclipse.jetty.annotations.ServletContainerInitializersStarter@3ebe4ccc: java.lang.NoClassDefFoundError: com/sun/jersey/spi/container/ResourceMethodDispatchAdapter
java.lang.NoClassDefFoundError: com/sun/jersey/spi/container/ResourceMethodDispatchAdapter
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at org.eclipse.jetty.webapp.WebAppClassLoader.findClass(WebAppClassLoader.java:510)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:441)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:403)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:86)
	at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:130)
	at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:65)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:274)
```

I tried to remove one of the dependencies, it worked fine. Can you please help me figure out what could be the conflict?

Thanks.

**Comment by vania-pooh** [comment]
@chandannj76723 please provide more details - what is the purpose of trying to start Jetty?

**Comment by baev** [comment]
Hi, thanks for suggestion. 

> But, when I try to start the Jetty server, I get an error.

In general it is not an Allure problem. I guess you can ask the question at SO
