### ISSUE TITLE
Allure Jenkins plugin Could not find any allure results

### ISSUE THREAD

**Issue by qianyiliushang** [allure-framework/allure-core#741]
allure configuration in pom.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.imo.test</groupId>
    <artifactId>UIAutomationTest</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <aspectj.version>1.8.8</aspectj.version>
        <allure.version>1.5.0-RC1</allure.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>ru.yandex.qatools.allure</groupId>
            <artifactId>allure-testng-adaptor</artifactId>
            <version>1.5.0-RC1</version>
            <exclusions>
                <exclusion>
                    <artifactId>junit</artifactId>
                    <groupId>junit</groupId>
                </exclusion>
            </exclusions>
        </dependency>


        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>3.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.2</version>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.8.21</version>
        </dependency>

        <dependency>
            <groupId>org.uncommons</groupId>
            <artifactId>reportng</artifactId>
            <version>1.1.4</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.testng</groupId>
                    <artifactId>testng</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>4.0-beta5</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <testFailureIgnore>true</testFailureIgnore>
                    <argLine>
                        -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                    </argLine>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>
            </plugin>


            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>9.2.10.v20150310</version>
                <configuration>
                    <httpConnector>
                        <port>8088</port>
                    </httpConnector>
                    <webAppSourceDirectory>${project.build.directory}/site/allure-maven-plugin</webAppSourceDirectory>
                    <stopKey>stop</stopKey>
                    <stopPort>1234</stopPort>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.3</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>2.10.3</version>
                <configuration>
                    <encoding>UTF-8</encoding>
                </configuration>
                <executions>
                    <execution>
                        <id>make-a-jar</id>
                        <goals>
                            <goal>javadoc</goal>
                        </goals>
                        <phase>test</phase>
                        <configuration>
                            <encoding>UTF-8</encoding>
                            <source>1.8</source>
                            <charset>UTF-8</charset>
                            <locale>zh_CN</locale>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <reporting>
            <excludeDefaults>true</excludeDefaults>
            <plugins>
                <plugin>
                    <groupId>ru.yandex.qatools.allure</groupId>
                    <artifactId>allure-maven-plugin</artifactId>
                    <version>2.5</version>
                </plugin>
            </plugins>
        </reporting>

</project>
```
And Allure jenkins plugin version is *d*

Allure report configuration in job as bellow
![image](https://cloud.githubusercontent.com/assets/6229122/12664386/09586440-c66a-11e5-9e28-4ffdbba41220.png)

Here is the jenkins console logs
```log
[INFO] Rendering site with org.apache.maven.skins:maven-default-skin:jar:1.0 skin.
[INFO] Skipped "Allure" report, file "allure-maven-plugin.html" already exists for the English version.
[INFO] Skipped "Allure" report, file "allure-maven-plugin.html" already exists for the English version.
[INFO] Generating "Allure" report    --- allure-maven-plugin:2.5
[INFO] Generate Allure report (aggregate) with version 1.5.0-RC1
[INFO] Generate Allure report to /Users/chenpengpeng/.jenkins/jobs/AllureTest/workspace/target/site/allure-maven-plugin
[INFO] Found results directory /Users/chenpengpeng/.jenkins/jobs/AllureTest/workspace/target/allure-results
[JENKINS] Archiving site from /Users/chenpengpeng/.jenkins/jobs/AllureTest/workspace/target/site to /Users/chenpengpeng/.jenkins/jobs/AllureTest/site
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:32 min
[INFO] Finished at: 2016-01-28T19:44:44+08:00
[INFO] Final Memory: 45M/185M
[INFO] ------------------------------------------------------------------------
[JENKINS] Archiving /Users/chenpengpeng/.jenkins/jobs/AllureTest/workspace/pom.xml to com.imo.test/UIAutomationTest/1.0-SNAPSHOT/UIAutomationTest-1.0-SNAPSHOT.pom
channel stopped
[workspace] $ /Users/chenpengpeng/.jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/allure/bin/allure generate "/Users/chenpengpeng/.jenkins/jobs/AllureTest/workspace/target/site/allure-maven-plugin" "/Users/chenpengpeng/.jenkins/jobs/AllureTest/workspace/allure2432843664794763646.tmp/environment" -o "/Users/chenpengpeng/.jenkins/jobs/AllureTest/workspace/allure2432843664794763646.tmp/allure-report"
Exception in thread "main" ru.yandex.qatools.allure.data.ReportGenerationException: Could not find any allure results
	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:58)
	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
	at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:48)
Command aborted due to exception {}.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at ru.yandex.qatools.allure.command.ReportGenerate.runUnsafe(ReportGenerate.java:48)
	at ru.yandex.qatools.allure.command.AbstractCommand.run(AbstractCommand.java:52)
	at ru.yandex.qatools.allure.CommandLine.main(CommandLine.java:46)
Build step 'Allure Report' marked build as failure
Finished: FAILURE
```

I do have allure reports generated, here's the tree of target directory 
```
├── allure-results
│   └── 3c1dc9d7-1b2e-421b-98b6-1b03faef394d-testsuite.xml
├── classes
│   ├── com
│   │   └── imo
│   │       ├── android
│   │       │   ├── AndroidClassName.class
│   │       │   ├── BaseTest.class
│   │       │   ├── DriverUtil.class
│   │       │   └── ImoAndroidDriver.class
│   │       ├── server
│   │       │   ├── AppiumServer$1.class
│   │       │   ├── AppiumServer.class
│   │       │   ├── BaseResponse.class
│   │       │   ├── Build.class
│   │       │   ├── MobileServer.class
│   │       │   ├── ServerArguments.class
│   │       │   ├── ServerStatusResponse.class
│   │       │   ├── Value.class
│   │       │   ├── arguments
│   │       │   │   ├── AppiumAndroidArguments.class
│   │       │   │   ├── AppiumCommonArguments.class
│   │       │   │   └── AppiumIOSArguments.class
│   │       │   ├── command
│   │       │   │   └── CommandManager.class
│   │       │   └── exceptions
│   │       │       ├── InvalidAppiumJavascriptException.class
│   │       │       ├── InvalidNodeExecutorException.class
│   │       │       ├── InvalidServerFileException.class
│   │       │       ├── ServerDirectoryNotFoundException.class
│   │       │       ├── ServerException.class
│   │       │       └── ServerTimeoutException.class
│   │       └── utils
│   │           ├── CapabilityUtil.class
│   │           ├── CaptchaCodeUtil.class
│   │           ├── CommonUtil.class
│   │           ├── ConfigUtil.class
│   │           ├── ElementUtil.class
│   │           ├── Log4J.class
│   │           ├── PropertyUtils.class
│   │           ├── RandomUtils.class
│   │           └── StringUtil.class
│   └── log4j2.xml
├── generated-sources
│   └── annotations
├── generated-test-sources
│   └── test-annotations
├── javadoc-bundle-options
│   ├── javadoc-options-javadoc-resources.xml
│   └── package-list
├── maven-status
│   └── maven-compiler-plugin
│       ├── compile
│       │   └── default-compile
│       │       ├── createdFiles.lst
│       │       └── inputFiles.lst
│       └── testCompile
│           └── default-testCompile
│               ├── createdFiles.lst
│               └── inputFiles.lst
├── site
│   ├── allure-maven-plugin
│   │   ├── css
│   │   │   └── app.css
│   │   ├── data
│   │   │   ├── 13dc76e74f23c9fa-testcase.json
│   │   │   ├── 1e3707f9ff2fe0a4-testcase.json
│   │   │   ├── 453c8bbc008255fa-testcase.json
│   │   │   ├── b217c12647ec5d01-testcase.json
│   │   │   ├── behaviors.json
│   │   │   ├── c53b1870bf2bae7-testcase.json
│   │   │   ├── defects.json
│   │   │   ├── eef478d817fbd63b-testcase.json
│   │   │   ├── graph.json
│   │   │   ├── plugins.json
│   │   │   ├── report.json
│   │   │   ├── timeline.json
│   │   │   ├── total.json
│   │   │   ├── widgets.json
│   │   │   └── xunit.json
│   │   ├── flash
│   │   │   └── clippy.swf
│   │   ├── img
│   │   │   ├── allure-logo.png
│   │   │   ├── favicon.ico
│   │   │   └── tests_passed.jpg
│   │   ├── index.html
│   │   ├── js
│   │   │   ├── app.js
│   │   │   ├── charts
│   │   │   │   ├── charts.js
│   │   │   │   ├── duration.js
│   │   │   │   ├── pie.js
│   │   │   │   ├── severityMap.js
│   │   │   │   └── timeline.js
│   │   │   ├── controllers.js
│   │   │   ├── directives.js
│   │   │   ├── filters.js
│   │   │   ├── overview
│   │   │   │   └── widgets.js
│   │   │   ├── pane
│   │   │   │   └── pane.js
│   │   │   ├── pluginApi.js
│   │   │   ├── scrollfix
│   │   │   │   └── scrollfix.js
│   │   │   ├── services.js
│   │   │   ├── table
│   │   │   │   └── table.js
│   │   │   └── testcase
│   │   │       ├── list.js
│   │   │       ├── provider.js
│   │   │       ├── statusSwitcher.js
│   │   │       └── testcase.js
│   │   ├── plugins
│   │   │   ├── behaviors
│   │   │   │   ├── en.json
│   │   │   │   ├── ptbr.json
│   │   │   │   ├── ru.json
│   │   │   │   ├── script.js
│   │   │   │   ├── tab.tpl.html
│   │   │   │   └── widget.tpl.html
│   │   │   ├── defects
│   │   │   │   ├── en.json
│   │   │   │   ├── ptbr.json
│   │   │   │   ├── ru.json
│   │   │   │   ├── script.js
│   │   │   │   ├── tab.tpl.html
│   │   │   │   └── widget.tpl.html
│   │   │   ├── environment
│   │   │   │   ├── en.json
│   │   │   │   ├── ptbr.json
│   │   │   │   ├── ru.json
│   │   │   │   └── script.js
│   │   │   ├── graph
│   │   │   │   ├── en.json
│   │   │   │   ├── ptbr.json
│   │   │   │   ├── ru.json
│   │   │   │   ├── script.js
│   │   │   │   └── tab.tpl.html
│   │   │   ├── timeline
│   │   │   │   ├── en.json
│   │   │   │   ├── ptbr.json
│   │   │   │   ├── ru.json
│   │   │   │   ├── script.js
│   │   │   │   └── tab.tpl.html
│   │   │   ├── total
│   │   │   │   └── script.js
│   │   │   └── xunit
│   │   │       ├── en.json
│   │   │       ├── ptbr.json
│   │   │       ├── ru.json
│   │   │       ├── script.js
│   │   │       ├── tab.tpl.html
│   │   │       ├── testrun.html
│   │   │       ├── testsuite.html
│   │   │       └── widget.tpl.html
│   │   ├── templates
│   │   │   ├── overview
│   │   │   │   ├── keyValue.html
│   │   │   │   └── total.html
│   │   │   ├── overview.html
│   │   │   ├── table
│   │   │   │   └── table.html
│   │   │   └── testcase
│   │   │       ├── attachment.html
│   │   │       ├── list.html
│   │   │       ├── status-switcher.html
│   │   │       ├── testcase.html
│   │   │       └── testcaseView.html
│   │   ├── translations
│   │   │   ├── en.json
│   │   │   ├── ptbr.json
│   │   │   └── ru.json
│   │   ├── vendor
│   │   │   ├── filesize.js
│   │   │   ├── localstorageprovider.js
│   │   │   └── messageformat
│   │   │       ├── en.js
│   │   │       ├── ptbr.js
│   │   │       └── ru.js
│   │   └── webjars
│   │       ├── Sortable
│   │       │   └── 1.2.0
│   │       │       ├── Sortable.min.js
│   │       │       └── ng-sortable.js
│   │       ├── angular-loading-bar
│   │       │   └── 0.6.0
│   │       │       └── loading-bar.js
│   │       ├── angular-translate
│   │       │   └── 2.6.0
│   │       │       └── angular-translate.js
│   │       ├── angular-translate-interpolation-messageformat
│   │       │   └── 0.1.2
│   │       │       └── angular-translate-interpolation-messageformat.js
│   │       ├── angular-translate-loader-partial
│   │       │   └── 2.6.0
│   │       │       └── angular-translate-loader-partial.js
│   │       ├── angular-ui-bootstrap
│   │       │   └── 0.11.2
│   │       │       └── ui-bootstrap-tpls.min.js
│   │       ├── angular-ui-router
│   │       │   └── 0.2.13
│   │       │       └── angular-ui-router.js
│   │       ├── angularjs
│   │       │   └── 1.2.26
│   │       │       ├── angular-animate.min.js
│   │       │       └── angular.min.js
│   │       ├── d3js
│   │       │   └── 3.4.11
│   │       │       └── d3.min.js
│   │       ├── font-awesome
│   │       │   └── 4.2.0
│   │       │       └── fonts
│   │       │           ├── FontAwesome.otf
│   │       │           ├── fontawesome-webfont.eot
│   │       │           ├── fontawesome-webfont.svg
│   │       │           ├── fontawesome-webfont.ttf
│   │       │           └── fontawesome-webfont.woff
│   │       ├── highlightjs
│   │       │   └── 8.2-1
│   │       │       └── highlight.min.js
│   │       ├── jquery
│   │       │   └── 2.1.1
│   │       │       └── jquery.min.js
│   │       └── messageformat.js
│   │           └── 0.1.4
│   │               └── messageformat.js
│   ├── allure-maven-plugin.html
│   ├── apidocs
│   │   ├── allclasses-frame.html
│   │   ├── allclasses-noframe.html
│   │   ├── com
│   │   │   └── imo
│   │   │       ├── android
│   │   │       │   ├── AndroidClassName.html
│   │   │       │   ├── BaseTest.html
│   │   │       │   ├── DriverUtil.html
│   │   │       │   ├── ImoAndroidDriver.html
│   │   │       │   ├── class-use
│   │   │       │   │   ├── AndroidClassName.html
│   │   │       │   │   ├── BaseTest.html
│   │   │       │   │   ├── DriverUtil.html
│   │   │       │   │   └── ImoAndroidDriver.html
│   │   │       │   ├── package-frame.html
│   │   │       │   ├── package-summary.html
│   │   │       │   ├── package-tree.html
│   │   │       │   └── package-use.html
│   │   │       ├── server
│   │   │       │   ├── AppiumServer.html
│   │   │       │   ├── BaseResponse.html
│   │   │       │   ├── MobileServer.html
│   │   │       │   ├── ServerArguments.html
│   │   │       │   ├── ServerStatusResponse.html
│   │   │       │   ├── arguments
│   │   │       │   │   ├── AppiumAndroidArguments.html
│   │   │       │   │   ├── AppiumCommonArguments.html
│   │   │       │   │   ├── AppiumIOSArguments.html
│   │   │       │   │   ├── class-use
│   │   │       │   │   │   ├── AppiumAndroidArguments.html
│   │   │       │   │   │   ├── AppiumCommonArguments.html
│   │   │       │   │   │   └── AppiumIOSArguments.html
│   │   │       │   │   ├── package-frame.html
│   │   │       │   │   ├── package-summary.html
│   │   │       │   │   ├── package-tree.html
│   │   │       │   │   └── package-use.html
│   │   │       │   ├── class-use
│   │   │       │   │   ├── AppiumServer.html
│   │   │       │   │   ├── BaseResponse.html
│   │   │       │   │   ├── MobileServer.html
│   │   │       │   │   ├── ServerArguments.html
│   │   │       │   │   └── ServerStatusResponse.html
│   │   │       │   ├── command
│   │   │       │   │   ├── CommandManager.html
│   │   │       │   │   ├── class-use
│   │   │       │   │   │   └── CommandManager.html
│   │   │       │   │   ├── package-frame.html
│   │   │       │   │   ├── package-summary.html
│   │   │       │   │   ├── package-tree.html
│   │   │       │   │   └── package-use.html
│   │   │       │   ├── exceptions
│   │   │       │   │   ├── InvalidAppiumJavascriptException.html
│   │   │       │   │   ├── InvalidNodeExecutorException.html
│   │   │       │   │   ├── InvalidServerFileException.html
│   │   │       │   │   ├── ServerDirectoryNotFoundException.html
│   │   │       │   │   ├── ServerException.html
│   │   │       │   │   ├── ServerTimeoutException.html
│   │   │       │   │   ├── class-use
│   │   │       │   │   │   ├── InvalidAppiumJavascriptException.html
│   │   │       │   │   │   ├── InvalidNodeExecutorException.html
│   │   │       │   │   │   ├── InvalidServerFileException.html
│   │   │       │   │   │   ├── ServerDirectoryNotFoundException.html
│   │   │       │   │   │   ├── ServerException.html
│   │   │       │   │   │   └── ServerTimeoutException.html
│   │   │       │   │   ├── package-frame.html
│   │   │       │   │   ├── package-summary.html
│   │   │       │   │   ├── package-tree.html
│   │   │       │   │   └── package-use.html
│   │   │       │   ├── package-frame.html
│   │   │       │   ├── package-summary.html
│   │   │       │   ├── package-tree.html
│   │   │       │   └── package-use.html
│   │   │       └── utils
│   │   │           ├── CapabilityUtil.html
│   │   │           ├── CaptchaCodeUtil.html
│   │   │           ├── CommonUtil.html
│   │   │           ├── ConfigUtil.html
│   │   │           ├── ElementUtil.html
│   │   │           ├── Log4J.html
│   │   │           ├── PropertyUtils.html
│   │   │           ├── RandomUtils.html
│   │   │           ├── StringUtil.html
│   │   │           ├── class-use
│   │   │           │   ├── CapabilityUtil.html
│   │   │           │   ├── CaptchaCodeUtil.html
│   │   │           │   ├── CommonUtil.html
│   │   │           │   ├── ConfigUtil.html
│   │   │           │   ├── ElementUtil.html
│   │   │           │   ├── Log4J.html
│   │   │           │   ├── PropertyUtils.html
│   │   │           │   ├── RandomUtils.html
│   │   │           │   └── StringUtil.html
│   │   │           ├── package-frame.html
│   │   │           ├── package-summary.html
│   │   │           ├── package-tree.html
│   │   │           └── package-use.html
│   │   ├── constant-values.html
│   │   ├── deprecated-list.html
│   │   ├── help-doc.html
│   │   ├── index-all.html
│   │   ├── index.html
│   │   ├── overview-frame.html
│   │   ├── overview-summary.html
│   │   ├── overview-tree.html
│   │   ├── package-list
│   │   ├── script.js
│   │   ├── serialized-form.html
│   │   └── stylesheet.css
│   ├── css
│   │   ├── maven-base.css
│   │   ├── maven-theme.css
│   │   ├── print.css
│   │   └── site.css
│   ├── images
│   │   ├── collapsed.gif
│   │   ├── expanded.gif
│   │   ├── external.png
│   │   ├── icon_error_sml.gif
│   │   ├── icon_info_sml.gif
│   │   ├── icon_success_sml.gif
│   │   ├── icon_warning_sml.gif
│   │   ├── logos
│   │   │   ├── build-by-maven-black.png
│   │   │   ├── build-by-maven-white.png
│   │   │   └── maven-feather.png
│   │   └── newwindow.png
│   └── project-reports.html
├── surefire-reports
│   ├── Surefire\ suite
│   │   ├── Surefire\ test.html
│   │   └── Surefire\ test.xml
│   ├── TEST-com.imo.testcases.android.loginregister.LoginTest.xml
│   ├── bullet_point.png
│   ├── collapseall.gif
│   ├── com.imo.testcases.android.loginregister.LoginTest.txt
│   ├── emailable-report.html
│   ├── failed.png
│   ├── index.html
│   ├── jquery-1.7.1.min.js
│   ├── junitreports
│   │   └── TEST-com.imo.testcases.android.loginregister.LoginTest.xml
│   ├── navigator-bullet.png
│   ├── old
│   │   ├── Surefire\ suite
│   │   │   ├── Surefire\ test.properties
│   │   │   ├── classes.html
│   │   │   ├── groups.html
│   │   │   ├── index.html
│   │   │   ├── main.html
│   │   │   ├── methods-alphabetical.html
│   │   │   ├── methods-not-run.html
│   │   │   ├── methods.html
│   │   │   ├── reporter-output.html
│   │   │   ├── testng.xml.html
│   │   │   └── toc.html
│   │   └── index.html
│   ├── passed.png
│   ├── skipped.png
│   ├── testng-reports.css
│   ├── testng-reports.js
│   ├── testng-results.xml
│   └── testng.css
├── test-classes
│   ├── com
│   │   └── imo
│   │       ├── data
│   │       │   └── AccountDataProvider.class
│   │       ├── pages
│   │       │   ├── BasePage.class
│   │       │   ├── HomePage.class
│   │       │   ├── SettingsPage.class
│   │       │   ├── WelcomePage.class
│   │       │   ├── contact
│   │       │   │   └── ContactHomePage.class
│   │       │   ├── contacts
│   │       │   │   ├── ContactHomePage.class
│   │       │   │   ├── DetailProfilePage.class
│   │       │   │   ├── IMPage.class
│   │       │   │   └── OrgContactPage.class
│   │       │   ├── home
│   │       │   │   └── WorkchatPage.class
│   │       │   ├── registerlogin
│   │       │   │   ├── CapchaPage.class
│   │       │   │   ├── LoginPage.class
│   │       │   │   ├── ProtocolPage.class
│   │       │   │   └── RegisterPage.class
│   │       │   └── task
│   │       │       └── TaskPage.class
│   │       ├── testcases
│   │       │   └── android
│   │       │       ├── PassWelcomeActivity.class
│   │       │       └── loginregister
│   │       │           └── LoginTest.class
│   │       └── widgets
│   │           └── home
│   │               └── ContactWindowWidget.class
│   ├── config.properties
│   └── imo7.0.1.apk
└── tmp
    └── jsp

117 directories, 312 files
```
when I user maven jetty plugin to access the report, everything goes well.

Please help to see if it's a bug of allure jenkins plugin or the configuration is wrong, thanks.

**Comment by qianyiliushang** [comment]
seems the attached image is down
The results directory configured in Allure Report is `target/site/allure-maven-plugin`
![image](https://cloud.githubusercontent.com/assets/6229122/12664719/faaef21c-c66c-11e5-9e61-50c5cd176171.png)

**Comment by vania-pooh** [comment]
How about using default value: ```target/allure-results```?

**Comment by qianyiliushang** [comment]
@vania-pooh  Yes, I  tried to use the default value `target/allure-resulsts`，but when I click on Allure Report link, the page keeps loading, the results does not displayed.
![image](https://cloud.githubusercontent.com/assets/6229122/12706511/e9a6b6d8-c8c1-11e5-9deb-92933af41367.png)

**Comment by just-boris** [comment]
It seems that you have latest version of Jenkins. It requires some special content-security setup. Please, refer [the documentation](http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin) for details. 
Also, the original issue is #715

**Comment by qianyiliushang** [comment]
Yes, it works ,thanks.
